mode: 'train'
exp_name: 'exp'
dataset: 'AudioCaps'
text_encoder: 'bert'
joint_embed: 1024
json_files: ["as_pretrain.json"]
dataset_folder: "/home/tienluong/multi-modal/dataset/AudioSet_waveform"
blacklist: "blacklist_exclude_test_ac.json"

wav:
  sr: 32000 
  window_size: 1024
  hop_length: 320
  mel_bins: 64
  max_length: 10

bert_encoder:
  type: 'bert-base-uncased'
  freeze: Yes

cnn_encoder:
  model: 'ResNet38'
  pretrained: Yes
  freeze: Yes

data:
  batch_size: 256
  num_workers: 8

training:
  epsilon: 0.05
  m: 0.95
  margin: 0.2
  freeze: No
  loss:  contrastive # 'triplet', 'weight', 'contrastive', 'pot', 'ntxent', 'wloss', 'ot'
  use_ot: False
  reg: 0
  spec_augmentation: Yes
  epochs: 10
  lr: !!float 1e-4
  clip_grad: 2
  seed: 1994
  resume: No
  l2_norm: Yes
  dropout: 0.2
  use_cosine: True
  noise_p: 0

path:
  vocabulary: 'data/{}/pickles/words_list.p'
  word2vec: 'pretrained_models/w2v_all_vocabulary.model'
  resume_model: "noisy-output/NTXent-baseline_data_AudioCaps_noise0_eps0.05_m0.95_lr_0.0001_/models"
